#ifndef ERRORS_H__
#define ERRORS_H__

// events
#define PHONE_EVENT 100

// completion codes
#define PHONE_OK 200

// warnings
#define PHONE_WARNING_EMPTY 400

// errors
#define PHONE_ERROR_FAILED 500
#define PHONE_ERROR_INVALID_STATE 501
#define PHONE_ERROR_PROTOCOL_VIOLATION 502
#define PHONE_ERROR_BUSY 503
#define PHONE_ERROR_NO_RESOURCE 504
#define PHONE_ERROR_NOT_FOUND 505
#define PHONE_ERROR_ABORTED 506
#define PHONE_ERROR_NOT_IMPLEMENTED 507
#define PHONE_ERROR_INVALID_ARGUMENT 508
#define PHONE_ERROR_TIMEOUT 509
#define PHONE_ERROR_NUMBER_CHANGED 510
#define PHONE_ERROR_UNREACHABLE 511
#define PHONE_ERROR_REJECTED 512
#define PHONE_ERROR_DISCONNECTED 513

// fatal errors
#define PHONE_FATAL_SYNTAX 600

#endif